name: CI

on:
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: meta
  TAG: latest

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "Hello World!"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository:  MetaCubeX/Clash.Meta
          fetch-depth: 0 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: debug
        run: |
          pwd && ls -al
      - name: login registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_ACCOUNT }}/${{secrets.DOCKERHUB_REPO}}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}