name: CI

on:
  workflow_dispatch:

env:
  REGISTRY: docker.io

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "Hello World!"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository:  MetaCubeX/Clash.Meta
          fetch-depth: 0 
      - name: debug
        run: |
          pwd && ls -al
      - name: login registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
